### ISSUE TITLE
Objects can have related objects.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-pcdm#14]

**Comment by jcoyne** [comment]
What predicate should be used for this?

**Comment by jcoyne** [comment]
Should this be a container or just an association?

**Comment by escowles** [comment]
It should be a container called "related" and use the predicate ore:aggregates.

**Comment by jcoyne** [comment]
@escowles I'm not sure that's possible. The object *IS* and aggregation. It would have to  aggregate related, and objects all together.

**Comment by elrayle** [comment]
There was a discussion about a potential implementation of this at a lower level [activefedora-aggregations - issue #11](https://github.com/projecthydra-labs/activefedora-aggregation/issues/11), but it was decided that it would be implemented at the PCDM level. 

## Summary

### Background:  
Groups of things in a Collection are...
* Collection pcdm:hasMember Collection
* Collection pcdm:hasMember Object
* Collection ore:aggregates Object (related object)

Groups of things in an Object are...
* Object pcdm:hasMember Object
* Object ore:aggregates Object (related object)
* Object pcdm:hasFile File
* Object pcdm:hasRelatedFile File (related file)

NOTE: hasFile and hasRelatedFile are not aggregations and therefore are not covered under the Proposed Solution.  See https://github.com/projecthydra-labs/hydra-pcdm/issues/19

### Proposed Solution:
#### Collections and Objects
Collections and objects will be in a single aggregation with predicate pcdm:hasMember.  This is consistent with the current implementation.

Defined by:
```
aggregates :members, :predicate => RDFVocabularies::PCDMTerms.hasMember, :class_name => "ActiveFedora::Base"
```
NOTE: The same approach will be used for Object pcdm:hasMember Object

#### Related Objects
The Collection object will have a property with predicate pcdm:hasRelatedObjects which will point to a pcdm:Object that serves as an ORE:aggregation of the related objects.

Defined by:
```
property :relatedObjects, predicate: RDFVocabularies::PCDMTerms.hasRelatedObjects
```
NOTE: The predicate is plural because it is a container for the related objects, not the related object itself.

NOTE: The same approach will be used for Object's related objects.

**Comment by terrellt** [comment]
`property :relatedObjects, predicate: RDFVocabularies::PCDMTerms.hasRelatedObjects, class_name: 'ActiveFedora::Base'` should work and do what you expect.

I think the relatedObject can just be a Hydra::Work too, which makes me happy.

**Comment by jcoyne** [comment]
@terrellt that doesn't seem like a solution, because it will not have order.

**Comment by terrellt** [comment]
> @terrellt that doesn't seem like a solution, because it will not have order.

class_name 'PCDM::Work' or whatever the class is would be more correct.

**Comment by azaroth42** [comment]
The proposed solution is exactly what the model currently says, so :+1: to the proposed solution :D

**Comment by elrayle** [comment]
@jcoyne My understanding was that the benefits of having a separate object aggregate the relatedObjects was...
* ability to request only related objects (as opposed to getting both related objects and members together)
* easier management of separate predicates
* and ability to apply order to the aggregation of related objects

Hydra::Works::GenericWork and GenericFile are both PCDM::Object so unless the code for Hydra::Works::GenericWork and/or GenericFile limits the aiblity of one or both of these to be used as related objects, then they would be able to serve as related objects.  That said, it doesn't mean that Sufia will surface this ability through its UI.

**Comment by terrellt** [comment]
@azaroth42 Do we need to mint a new predicate for "hasRelatedObjects" (the plural) within PCDM?

**Comment by escowles** [comment]
I thought the model said each pcdm:Object should have a container (not a pcdm:Object) that contained proxies for related objects, called {object}/related/, and that the property used to link to the related objects would be ore:aggregates.

**Comment by escowles** [comment]
BTW, I'm working from this Google doc:

https://docs.google.com/document/d/1RI8aX8XQEk-30-Ht-DaPF5nz_VtI1-eqxUuDvF3nhv0/edit#

Is this still the latest LDP-implementation-of-PCDM spec?

**Comment by terrellt** [comment]
@escowles That works except in the case that you want to order related objects separately from member objects.

**Comment by azaroth42** [comment]
Use case for ordered related objects? Use cases to date have not required
ordering there at all.

**Comment by terrellt** [comment]
@azaroth42 I can make some up, but who knows if they'd be used (Collection Documents Page 1). Right now it's more of an implementation detail - if we use ore:aggregates then there's no reason those documents shouldn't be able to be ordered, but right now there's a tight couple between member updating and ordering.

**Comment by escowles** [comment]
Is the issue that there can only be one iana:first/iana:last on a pcdm:Object, so we can only have one ordered set?  Do we need to make the files/, members/, and related/ containers ore:Aggregations?  Then each could have its own ordering?

**Comment by terrellt** [comment]
@escowles Files aren't aggregated, but yes - that's the issue. We could make members/ and related/ ore:aggregations, but that's counter-PCDM and we'd have to figure out the relations

**Comment by azaroth42** [comment]
Until someone has a valid use case that is shared by two or more
institutions,  I propose that this is not an issue for a *baseline shared
model*, which is what PCDM is.

**Comment by escowles** [comment]
@azaroth42, that's fine with me.  So for now we can say that the members/ container is ordered, and all of the others are unordered.

**Comment by azaroth42** [comment]
+1. Is able to be ordered.

**Comment by escowles** [comment]
Yes, important correction: members/ is able to be ordered, the others are unordered.

**Comment by jcoyne** [comment]
I think this ticket is actually invalid. hasRelatedObject is not part of PCDM.
See examples:
https://github.com/projecthydra-labs/hydra-pcdm/issues/14

**Comment by elrayle** [comment]
I agree that the document currently does not describe the proposed solution.  If the proposed solution is acceptable, then the application profile should be updated to reflect this.

**Comment by escowles** [comment]
The examples do include a related file:

https://wiki.duraspace.org/display/FF/PCDM+Examples#PCDMExamples-Multi-PageTextshowingcontainedandrelatedfiles,memberandaggregatedobjects

The mods.xml file is a related file, linked to with ore:aggregates.

**Comment by jcoyne** [comment]
@escowles this ticket is for related objects, not related files. Related files is #62

**Comment by terrellt** [comment]
So proposals:

1. Use ore:aggregates to link objects which are related. DO NOT order. Don't necessarily use indirect containers (why would you? Don't need proxies)
2. Use some property which doesn't imply ordering is allowed.
3. Use a predicate to point to a Work which encapsulates a collection's related objects, and hasMember from there.

**Comment by escowles** [comment]
@jcoyne I've updated the diagram to have a related object (donor agreement) linked with ore:aggregates: https://wiki.duraspace.org/display/FF/PCDM+Examples#PCDMExamples-Multi-PageTextshowingcontainedandrelatedfiles,memberandaggregatedobjects
