### ISSUE TITLE
Add contains files to Hydra::PCDM::Interfaces::Object

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/hydra-pcdm#5]
Hydra::PCDM::Interfaces::Object (this is a module)
   Should be able to contains pcdm:File using the pcdm:hasFile (eg Hydra::PCDM::GenericFile) 

* The files should live at a sub uri of the pcdm:Object (This is AF::Base contains)
* There should be a pcdm:has_file assertion on the object that points at the file (This is AF::Base:has_and_belongs_to_many)
* This task should figure out how to combine the behaviors above
* There can be zero to many files
* the path to the file subnode can be auto generated

**Comment by awead** [comment]
I don't know if `has_and_belongs_to_many` implements LDP direct containment.

**Comment by flyingzumwalt** [comment]
Is this a repetition of #23?

**Comment by awead** [comment]
@flyingzumwalt it's tangentally related, but probably pertains more to what @elrayle is doing with the finishing the modeling.

**Comment by jcoyne** [comment]
Do we need to have more than?
```ruby
        contains "content", class_name: 'FileContentDatastream'
        contains "thumbnail"
```

**Comment by awead** [comment]
@jcoyne if that does the `/files` direct container URI to do the containment, then no.

**Comment by jcoyne** [comment]
Hmmm, yeah, it also doesn't set hasFile, just ldp:contains.

**Comment by awead** [comment]
@jcoyne right. can we do something like `aggregates :files` ? But that creates in indirect container. The examples I'm seeing have `/files` as a direct container.

**Comment by elrayle** [comment]
My first instinct is to say, avoid aggregates since the model discussions I've been in have not treated files as an aggregation.  Issues and questions...
* Is contains a concept that is already solidly in Fedora?  Is there a method that gets called to add files to the contains relationship?  (similar to aggregates for hasMembers)
* Do we ever want order to the list of files?  NOTE: order will be tricky because GenericFiles which contains Files already has an ordered aggregation.  Since the PCDM::Object can have only one aggregation with a head (IANA.first), we can't have two separate ordered aggregations for the same subject (the PCDM::Object).

**Comment by awead** [comment]
@elrayle `contains` translates to a ldp basic container. For files, we need the hasFile predicate, and therefore a ldp direct container. I don't believe the PCDM model allows for ordering at the hasFile level, so we should be safe there.
